### ISSUE TITLE
"NameError: name 'adata' is not defined" for two quality metrics

### ISSUE THREAD

**Issue by krademaker** [Moldia/Xenium_benchmarking#10]
Hi,

Thanks for publishing the code, it's been very useful to run some benchmarks on segmentation on our own Xenium data. I ran into two small issues with quality metrics being calculated, where the functions [percentile_95th_reads_cells](https://github.com/Moldia/Xenium_benchmarking/blob/3b38701f7f43c5b4767f1b41fa9e55d45d633b53/xb/_quality_metrics.py#L202) and [percentile_5th_reads_cells](https://github.com/Moldia/Xenium_benchmarking/blob/3b38701f7f43c5b4767f1b41fa9e55d45d633b53/xb/_quality_metrics.py#L119) have the parameter named `adata_sp` but the code uses `adata` instead.

Best,
Koen

**Comment by sergiomarco25** [comment]
Hi,
Sorry for the typo. It's been corrected now.

**Comment by krademaker** [comment]
Brilliant, thanks!
