### ISSUE TITLE
txsim module used in 1_1 cannot be found/installed

### ISSUE THREAD

**Issue by z5ouyang** [Moldia/Xenium_benchmarking#8]
Dear author,
Very good package of the benchmarking. I have a quick question:
How/where to find the python module 'txsim' used in 1_1?

Thanks!

**Comment by sergiomarco25** [comment]
The txim module is still not accessible to everybody. We'll modify very soon the available code to include the requires functions of that package in our own library instead.

**Comment by sergiomarco25** [comment]
We have now modified the code so that there is no requirement for txsim
